# version: '3.9'

services:
  app:
    build: .
    container_name: rails_web_app
    depends_on:
      - db
      - redis
      - sidekiq
    tty: true
    environment:
      RAILS_ENV: development
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    # we use plugin :tailwindcss if ENV.fetch("RAILS_ENV", "development") == "development"  run tailwind in background
    # check https://github.com/rails/tailwindcss-rails for more info
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
  db:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sidekiq:
    build: .
    container_name: sidekiq_worker
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
    volumes:
      - .:/rails
    command: bundle exec sidekiq

volumes:
  mongo_data:
  redis_data:
